[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "VideoPreview"
version = "0.1.0"
description = "A video preview tool."
authors = [{ name = "yeehua", email = "yeehua@live.cn" }]
dependencies = [
    "Kivy>=2.3.1",       # GUI框架
    "python-vlc>=3.0.0",    # 视频播放（跨平台支持）
    "Pillow>=10.0.0",       # 缩略图生成
    "numpy>=1.21",          # 图像处理（配合OpenCV可选）
]
optional-dependencies = {
    "opencv" = ["opencv-python>=4.7.0"]  # 可选：用于高级帧处理
}